### ISSUE TITLE
Create VIF with MAC

### ISSUE THREAD

**Issue by fmbiete** [fog/fog-xenserver#42]
Hi,

I'm trying to create a VIF with a custom MAC address (since later is not possible to change it). But the mac address is silently discarded:

```
connection.vifs.create(server: vm_object, network: network_object, MAC: 'mac address')
connection.vifs.create(server: vm_object, network: network_object, mac: 'mac address')
```

Both will create a vif but with autogenerated MAC.

**Comment by kaizoku0506** [comment]
Is there a reason you want a specific MAC address?  You can query by VM name / uuid and return the generated one.  You just do:

server = connection.servers.find { |server| server.uuid == #{uuid} }
Mac = server.vifs.mac.first

**Comment by fmbiete** [comment]
Yes, I need to use a specific MAC because I will be using a static DHCP server, and the MAC will tell some attributes (DNS, gateway...).
For example if the MAC starts with 02:01 thats CPD 02 client 01, use their config.

**Comment by plribeiro3000** [comment]
@fmbiete I'm not sure the reason behind this. When using fog i had this same behavior so i guess it was just extracted as well. Perhaps you have time to dig it further?

**Comment by fmbiete** [comment]
The problem was that I only had fog in my Gemfile, adding fog-xenserver fixes the xenserver support in fog, and the MAC is added at creation time.

Sorry for this.

**Comment by plribeiro3000** [comment]
@fmbiete. Awesome to know. Thanks
