### ISSUE TITLE
Unplug vif

### ISSUE THREAD

**Issue by fmbiete** [fog/fog-xenserver#44]
This is more a question, so sorry beforehand:

How can I plug/unplug a VIF?
There is a plug_vif and unplug_vif but I don't know what object has it.

Thanks

**Comment by plribeiro3000** [comment]
So the main intention here is to make everything feel more encapsulated. So instead of calling the requests directly from the connections object you can call them directly on the objects.

Since its a vif method you can call it directly on the `vif` object.

```ruby
# handle connection
@connection = 'bla bla bla'

# load the vif
@vif = @connections.vifs.first

# plug the vif
@vif.plug

# unplug the vif
@vif.unplug
```

**Comment by plribeiro3000** [comment]
Let me know if you have more questions. Thanks!
