### ISSUE TITLE
VM revert snapshot - undefined method revert_to_vm

### ISSUE THREAD

**Issue by fmbiete** [fog/fog-xenserver#46]
Hi,

I'm trying to revert server to one snapshot, but I'm getting an error.
Maybe the alias_method is not working?
```
vm.revert_to(snapshot.uuid)

NoMethodError: undefined method `revert_to_vm' for #<Fog::Compute::XenServer::Real:0x007f3808b0e360>
        from /usr/local/bundle/gems/fog-xenserver-0.1.1/lib/fog/compute/xen_server/models/server.rb:168:in `revert_to'
```

**Comment by plribeiro3000** [comment]
@fmbiete Try the latest version `0.1.2`. It should have this issue fixed.

**Comment by fmbiete** [comment]
Hi,

The problem is fixed.

Thanks!!!

**Comment by plribeiro3000** [comment]
Note you can use bot `revert` and `revert_to` methods. =)
