### ISSUE TITLE
VM affinity not working

### ISSUE THREAD

**Issue by hanej** [fog/fog-xenserver#53]
We're using the foreman-xen plugin (which uses this under the covers) for The Foreman to build VMs on multiple Xen clusters.  It seems the affinity is not working correctly and always builds on the master node.  No matter what slave the affinity is set to it seems to be ignored.  Have you experienced this problem?

When using the Java API years ago we had the same issue so I don't think it's specific to your code, just hoping you've come across this and had an answer.

**Comment by plribeiro3000** [comment]
Hey @hanej . I never had this problem so far.

Just looked at the code and could not find anything that could replicate this behaviour. Perhaps it is XEN related?

Thanks!

**Comment by hanej** [comment]
Thank you for checking.  I posted this question on the XenServer discussion forums too.  Hopefully we figure it out.

Very nice library though!  It works well.

**Comment by plribeiro3000** [comment]
Thank you @hanej . Thats awesome to have feedback. Could you post the link of the forum here plz?

Thanks!

**Comment by hanej** [comment]
The link is

http://discussions.citrix.com/topic/373231-vm-affinity-not-working/

**Comment by fernandes** [comment]
@hanej this weekend playing with xenserver 6.5 I got the same thing as you mentioned

as Tobias mentioned on the forum, you need to set the affinity for the vm being created, so this will work:

```ruby
template.class
# => Fog::Compute::XenServer::Models::Server
template.affinity = conn.hosts[0]
template.save
# true
```

hope this may help you
