### ISSUE TITLE
NokogiriStreamParser at top level?

### ISSUE THREAD

**Issue by nirvdrum** [fog/fog-xenserver#56]
I noticed that the autoload for `Fog::XenServer::NokogiriStreamParser` loads `::NokogiriStreamParser` rather than a class in the `Fog::XenServer` namespace. This might be legitimate, in which case please feel free to close the issue. But it looks like a potential oversight.

**Comment by plribeiro3000** [comment]
Yeap. Thats a typo. =s

**Comment by plribeiro3000** [comment]
Fixed on 6a7f4eafbdca6891d00ca42802c4f9d8e40f6b3a
