### ISSUE TITLE
fog-xenserver missing things from original fog/xenserver?

### ISSUE THREAD

**Issue by mmoll** [fog/fog-xenserver#59]
In http://projects.theforeman.org/issues/14696#change-67041 a user reported regressions from switching to a higher fog version, which requires the usage of the modularized fog-xenserver. After a quick glance, it seems that some things are missing from the original xenserver module coming from the original fog, e.g. the redirect_to_master parameter. How should this be dealt with?

The original problem is that after updating to a newer fog version, the xenserver plugin for Foreman stops to work, without throwing any obvious errors, and now I think it's because "something" is missing/different compared to the original xenserver stuff that was included in fog.

**Comment by fernandes** [comment]
hi @mmoll 

a few months (I think two years) ago, we refactored to a better organization and to support the whole XenServer API, could you please provide a detailed code snippet for this use case? (I read the issue but I'm kinda lost on getting the whole picture)

**Comment by plribeiro3000** [comment]
@mmoll Yeah. Some stuff changed on purpose but i don't think thats the case to what you are saying. Can you elaborate?

The Server creation changed by a lot. Before it was creating a log of resources with just one call and that was really bad to maintain so we dropped that. Now you need to create each of the required resources by XenServer individually. 

If thats not what you are having, can you please describe which XenServer call are you trying to make?

**Comment by mmoll** [comment]
The code in question is i.e. https://github.com/theforeman/foreman-xen/blob/master/app/models/foreman_xen/xenserver.rb#L194

Is there any documentation, what changed?

**Comment by plribeiro3000** [comment]
Yeah. Thats the exact code that changed. Prior you could pass the network and the disk and it would create everything for you. Now you need to manually create them after creating the VM and then provision.

@fernandes Do you have a snippet for VM creation you can share here?

**Comment by fernandes** [comment]
I extracted our system provisioning into a single procedure, maybe I missed some detail, but it's a good starting point, if anything else is missing, please tell me so I can update the gist to become a good reference

here is the [gist](https://gist.github.com/fernandes/a9e89c43af4f5ef9de229393e17de7bd)

**Comment by mmoll** [comment]
seems to be fixed with theforeman/foreman-xen@9e5f80d

**Comment by plribeiro3000** [comment]
:+1:

Em ter, 30 de ago de 2016 20:03, Michael Moll <notifications@github.com>
escreveu:

**Comment by fernandes** [comment]
hi @mmoll,

congrats on the hard work 🙇! happy everything is ok now.

If there's something we can help, please get in touch.

**Comment by mmoll** [comment]
all props to @alejandrocfg :dancers:

**Comment by fernandes** [comment]
@alejandrocfg 👏 🎉 😎
