### ISSUE TITLE
Fixnum is deprecated in Ruby 2.4.0

### ISSUE THREAD

**Issue by espen** [fog/fog-xenserver#62]
```lib/fog/utilities.rb:4: warning: constant ::Fixnum is deprecated```

**Comment by thechrisoshow** [comment]
I've added a pull request that fixes this: https://github.com/fog/fog-xenserver/pull/63

**Comment by lightningspirit** [comment]
As the fix is already merged, shouldn't this issue be closed? @thechrisoshow  @espen

**Comment by plribeiro3000** [comment]
You are right! Thanks for noting!
